<?php $this->init(); ?>
<div> Pridėti teksta galima cia</div>

<script type="text/javascript" src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>
<div id="SkypeButton_Call_algirdziokaszzz_1">
    <script type="text/javascript">
        Skype.ui({
            "name": "<?php $this->name_id ?>",
            "element": "SkypeButton_Call_algirdziokaszzz_1",
            "participants": ["algirdziokaszzz"],
            "imageSize": 32
        });
    </script>
</div>


